### ISSUE TITLE
でっけぇときにうごかねぇわ

### ISSUE THREAD

**Issue by minari515** [FUJI-CORPORATION-GROUP/parcel_allocation#21]
- [x] 原因追及
- [x] どこがわるいかさがそうね
  - [x] 面積計算
  - [x] 線分上の交点判定

**Comment by banamon** [comment]
座標がマイナスを含む際に，2分探索の計算中になんかおかしい
面積計算がおかしい？

**Comment by banamon** [comment]
DXFから実行したときに表示されない
めっちゃ範囲が広い時がある（三角形になっている？）
