### ISSUE TITLE
directory構成の整理

### ISSUE THREAD

**Issue by tagahei** [FUJI-CORPORATION-GROUP/parcel_allocation#76]
モジュール関係が面倒くさそう
- [ ] github の rootディレクトリを今の外部変形にしよう
- [ ] 不要なファイルの削除
- [ ] ディレクトリ名・ファイル名検討

**Comment by banamon** [comment]
## ルートディレクトリの変更

- [gitのコマンドドキュメント](https://git-scm.com/book/ja/v2/Git-%E3%81%AE%E3%81%95%E3%81%BE%E3%81%96%E3%81%BE%E3%81%AA%E3%83%84%E3%83%BC%E3%83%AB-%E6%AD%B4%E5%8F%B2%E3%81%AE%E6%9B%B8%E3%81%8D%E6%8F%9B%E3%81%88#%E6%9C%80%E5%BC%B7%E3%81%AE%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3:-filter-branch)
- [gitリポジトリのルートディレクトリを得るスクリプト](https://qiita.com/dalance/items/b04c288d8dde06ce2b59)

**Comment by tagahei** [comment]
結構前に終わってた
こんな感じになってます

![image](https://github.com/user-attachments/assets/335ed583-6974-471e-972f-97f3d1735d33)
