### ISSUE TITLE
マルチポリゴンissue

### ISSUE THREAD

**Issue by banamon** [FUJI-CORPORATION-GROUP/parcel_allocation#94]
## 概要
last_remain_frameとremain_site_frameを合成し，ポリゴンを生成する際に，
演算上で座標が一致していないことからそれぞれが別の図形と認識され，
複数のポリゴン（マルチポリゴン）になってしまう問題

## 再現手順
大体5回に4回ぐらい発言するから誰でも見れるよ
どうやら細かい数値の部分で，完全には一致していない座標があることが問題と考えられる

## 原因
座標の不一致

## 参考
- [shapely doc](https://shapely.readthedocs.io/en/stable/manual.html)
- [MultiPolygon](https://shapely.readthedocs.io/en/stable/manual.html#MultiPolygon)

**Comment by minari515** [comment]
`last_remain_frame:<components.frame.Frame object at 0x00000254A444DF70>
last_remain_frame.points: (6, 15421) (8, 21699) (4565, 21695) (4560, 14910)
remain_site_frame:<components.frame.Frame object at 0x00000254A44C68E0>
remain_site_frame.points: (74042, 7284) (72743, 3036) (72590, 2949) (72586, 7285) (72580, 15475)
remain_search_polygon:MULTIPOLYGON (((72580.66123021481 15475.517535981337, 74042.28839344875 7284.790388134192, 72743.68779471051 3036.413513700723, 72590.02029214716 2949.912331173267, 72580.66123021481 15475.517535981337)), ((6.251638457643004 15421.290344323312, 8.796587178199843 21699.06750578729, 4565.275725687456 21695.631124396295, 4560.158816962225 14910.852251697035, 6.251638457643004 15421.290344323312)))`

上手くいかないとき

**Comment by minari515** [comment]
`last_remain_frame:<components.frame.Frame object at 0x0000025344596EE0>
last_remain_frame.points: (76343, 14812) (76343, 14812) (76343, 14812)
remain_site_frame:<components.frame.Frame object at 0x0000025344575D00>
remain_site_frame.points: (76343, 14812) (77535, 18712) (74768, 21642) (8, 21699) (5, 14755)
remain_search_polygon:POLYGON ((5.981614636937297 14755.206442127188, 8.796587178199843 21699.06750578729, 74768.50760242401 21642.68562145959, 77535.4574802566 18712.70654749819, 76343.20401126123 14812.244718769212, 5.981614636937297 14755.206442127188))  `


うまくいくとき

**Comment by minari515** [comment]
座標の一致の問題なので，手法を変える（区画を削除する方向に転換する）とかが必要かも

**Comment by minari515** [comment]
一旦とりあえず今まで通りの敷地のあまり＋探索領域のあまりの路線で考えた


### 方法
ちょっとだけ図形に余裕をもって計算してみる

`
# ポリゴンを少し膨張させて結合
buffered_polygonA = polygonA.buffer(1)  # 必要に応じて調整
buffered_polygonB = polygonB.buffer(1)

combined_polygon = unary_union([buffered_polygonA, buffered_polygonB])
`

図形にバッファを持たせて，多少拡張したものを参考にして計算する方法ですね
閾値を決める方法が分からないのと，どこまで行ってもいつかエラーが出るかもしれないという可能性を包含する特徴があります

1に設定すると体感半分ぐらいでマルチポリゴンエラーが出ました．
全部無理だったらマルチポリゴンだと遡及して数値を一個ずつ増やす感じにしてみよ

**Comment by minari515** [comment]
次は敷地 - 決定した区画の路線での考えかた

### 方法

引数を敷地と完成した区画に変更して計算．differenceってやつを使ってやりました
```
        for frame in frame_list:
            frame_polygon = Polygon(Point.to_np_array_list(frame.points))
            site_frame = site_frame.difference(frame_polygon)
```

### 結果
普通にマルチポリゴンは出ますね．というか区画の数分計算するせいか試行回数が上がって隔日にマルポリ化します
もはやそれすら超えてジオメトリーになったりもします

一応ログも共有しときます
```ログ
site_frame:GEOMETRYCOLLECTION (LINESTRING (6.119519297154872 15095.384112262684, 0 0), POLYGON ((74768.50760242401 21642.68562145959, 77535.4574802566 18712.70654749819, 72743.68779471051 3036.413513700723, 67439.0810053181 50.390102950719665, 51437.442423521614 38.43376838184634, 58319.60470704127 43.57608142675228, 58308.32553044104 15138.94719348148, 51426.163246921395 15133.804880436574, 44445.271691401984 15128.588797433564, 36748.57233134793 15122.837866855147, 28807.681738268817 15116.904477957482, 21076.027531767482 15111.127429313918, 13894.53445578232 15105.76145798032, 6799.705005728567 15100.460241221777, 6.119519297154872 15095.384112262684, 8.796587178199843 21699.06750578729, 74768.50760242401 21642.68562145959)), POLYGON ((38042.63473462383 28.42524323015538, 28818.96091486904 21.53336590275452, 36759.85150794816 27.466754800419125, 38042.63473462383 28.42524323015538)), POLYGON ((22647.30038569429 16.921935782325022, 13905.813632382535 10.390345925592015, 21087.3067083677 15.756317259190649, 22647.30038569429 16.921935782325022)))
```

**Comment by minari515** [comment]
というわけでバッファを増加させる方向にかじを切ってみた

```
        # 単一のポリゴンが得られるまでループ
        while True:
            # バッファを適用してポリゴンを生成
            buffered_last_remain_polygon = last_remain_polygon.buffer(buffer_distance)
            buffered_remain_site_polygon = remain_site_polygon.buffer(buffer_distance)
            
            # ポリゴンの結合
            remain_search_polygon = shapely.unary_union([buffered_last_remain_polygon, buffered_remain_site_polygon])
            
            # 結合後のポリゴンが単一のポリゴンであるか確認
            if remain_search_polygon.is_simple and remain_search_polygon.geom_type == 'Polygon':
                # 正規化と簡略化
                remain_search_polygon = remain_search_polygon.normalize().simplify(tolerance)
                break
            
            # バッファの値を増やして再計算
            buffer_distance += 1
```
単一のポリゴンになるまで幅を持たせながら進める方向で何回も計算してみたらおもしろいのができた

![image](https://github.com/FUJI-CORPORATION-GROUP/parcel_allocation/assets/126942302/bbe75a0f-b0f8-4dde-b097-d8a0840e6750)

**Comment by minari515** [comment]
ちなみに

```
# ポリゴン同士の交差判定
        if not last_remain_polygon.intersects(remain_site_polygon):
            print("探索領域と残りの敷地が交差していません")
```

上記のコードで交差判定をして，重なってないときっていう変更をしてみようとしたりもした
けど普通に交差判定は全部通ってるから全然だめ

**Comment by minari515** [comment]
```
distance = polygonA.distance(polygonB)
print(f"Distance between polygons: {distance}")
```


ポリゴン間の距離を出すってやつもあってそれもやってみたけど全部0にはなってるね
ややこしすぎる

**Comment by banamon** [comment]
## マルチポリゴンを描写する

参考
- [geopandasで複数のポリゴンを結合して描画する](https://qiita.com/HidKamiya/items/30c0620ded6013979cad)

**Comment by banamon** [comment]
## 2種類のマルチポリゴン
正常に行ったけど最後の残り結合でエラー履いている
![image](https://github.com/FUJI-CORPORATION-GROUP/parcel_allocation/assets/120772851/5d739e4c-3583-415f-898e-c0964832a3e8)

そもそも不正なマルチポリゴン
![image](https://github.com/FUJI-CORPORATION-GROUP/parcel_allocation/assets/120772851/08befb64-2677-45b0-be3f-b9726a69464e)
